//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiaoTian_Cup.Dictionary {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilePath {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilePath() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiaoTian_Cup.Dictionary.FilePath", typeof(FilePath).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/后出指挥官列表.csv 的本地化字符串。
        /// </summary>
        internal static string afterCommanderFilePath {
            get {
                return ResourceManager.GetString("afterCommanderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/电脑AI.csv 的本地化字符串。
        /// </summary>
        internal static string aIFilePath {
            get {
                return ResourceManager.GetString("aIFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/多线因子基础库.csv 的本地化字符串。
        /// </summary>
        internal static string baseMultiFactorFilePath {
            get {
                return ResourceManager.GetString("baseMultiFactorFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/纯正面因子基础库.csv 的本地化字符串。
        /// </summary>
        internal static string baseNegativeFactorFilePath {
            get {
                return ResourceManager.GetString("baseNegativeFactorFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/先出指挥官列表.csv 的本地化字符串。
        /// </summary>
        internal static string beforeCommanderFilePath {
            get {
                return ResourceManager.GetString("beforeCommanderFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /LiaoTian_Cup;component/Resources/commander/ 的本地化字符串。
        /// </summary>
        internal static string commanderDir {
            get {
                return ResourceManager.GetString("commanderDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /LiaoTian_Cup;component/Resources/factor/ 的本地化字符串。
        /// </summary>
        internal static string factorDir {
            get {
                return ResourceManager.GetString("factorDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /LiaoTian_Cup;component/Resources/maps/ 的本地化字符串。
        /// </summary>
        internal static string mapDir {
            get {
                return ResourceManager.GetString("mapDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/所有地图.csv 的本地化字符串。
        /// </summary>
        internal static string mapsFilePath {
            get {
                return ResourceManager.GetString("mapsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/突变因子列表.csv 的本地化字符串。
        /// </summary>
        internal static string mutationFactorPath {
            get {
                return ResourceManager.GetString("mutationFactorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/自选突变列表.csv 的本地化字符串。
        /// </summary>
        internal static string mutationFilePath {
            get {
                return ResourceManager.GetString("mutationFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/正面因子库.csv 的本地化字符串。
        /// </summary>
        internal static string negativeFactorFilePath {
            get {
                return ResourceManager.GetString("negativeFactorFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ./Resources/group_FactorList_Score.csv 的本地化字符串。
        /// </summary>
        internal static string scoreFactorPath {
            get {
                return ResourceManager.GetString("scoreFactorPath", resourceCulture);
            }
        }
    }
}
