//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiaoTian_Cup.Dictionary.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiaoTian_Cup.Dictionary.I18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to menu 的本地化字符串。
        /// </summary>
        public static string BackMenuBtn {
            get {
                return ResourceManager.GetString("BackMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right click to ban 的本地化字符串。
        /// </summary>
        public static string BanTip {
            get {
                return ResourceManager.GetString("BanTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic mutators: 的本地化字符串。
        /// </summary>
        public static string BaseMutator {
            get {
                return ResourceManager.GetString("BaseMutator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick more basic mutators 的本地化字符串。
        /// </summary>
        public static string BaseMutatorsWarn {
            get {
                return ResourceManager.GetString("BaseMutatorsWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vincent&apos;s Game 的本地化字符串。
        /// </summary>
        public static string BraveMode {
            get {
                return ResourceManager.GetString("BraveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick 2 Cmdrs. in Co-op mode 的本地化字符串。
        /// </summary>
        public static string CommanderWarn1 {
            get {
                return ResourceManager.GetString("CommanderWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick commander 的本地化字符串。
        /// </summary>
        public static string CommanderWarn2 {
            get {
                return ResourceManager.GetString("CommanderWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick 2 Cmdrs. in Nexus co-op mode 的本地化字符串。
        /// </summary>
        public static string CommanderWarnHub {
            get {
                return ResourceManager.GetString("CommanderWarnHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick 2 Cmdrs. in Usuck mode 的本地化字符串。
        /// </summary>
        public static string CommanderWarnUsuck {
            get {
                return ResourceManager.GetString("CommanderWarnUsuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm base&apos;s 的本地化字符串。
        /// </summary>
        public static string ConfirmBaseBtn {
            get {
                return ResourceManager.GetString("ConfirmBaseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string ConfirmBtn {
            get {
                return ResourceManager.GetString("ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm map 的本地化字符串。
        /// </summary>
        public static string ConfirmMapBtn {
            get {
                return ResourceManager.GetString("ConfirmMapBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Co-op mode 的本地化字符串。
        /// </summary>
        public static string DoublesMode {
            get {
                return ResourceManager.GetString("DoublesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 mutators mode 的本地化字符串。
        /// </summary>
        public static string EightMutatorsMode {
            get {
                return ResourceManager.GetString("EightMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 mutators mode 的本地化字符串。
        /// </summary>
        public static string FiveMutatorsMode {
            get {
                return ResourceManager.GetString("FiveMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free choice mutators: 的本地化字符串。
        /// </summary>
        public static string FreeMutator {
            get {
                return ResourceManager.GetString("FreeMutator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 mutators mode will need you pick 2 free choice mutators 的本地化字符串。
        /// </summary>
        public static string FreeMutatorsWarn1 {
            get {
                return ResourceManager.GetString("FreeMutatorsWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 mutators mode will need you pick 3 free choice mutators 的本地化字符串。
        /// </summary>
        public static string FreeMutatorsWarn2 {
            get {
                return ResourceManager.GetString("FreeMutatorsWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 mutators mode will need you pick 5 free choice mutators 的本地化字符串。
        /// </summary>
        public static string FreeMutatorsWarn3 {
            get {
                return ResourceManager.GetString("FreeMutatorsWarn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 mutators mode will need you pick 4 free choice mutators 的本地化字符串。
        /// </summary>
        public static string FreeMutatorsWarn4 {
            get {
                return ResourceManager.GetString("FreeMutatorsWarn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Banned mutators: 的本地化字符串。
        /// </summary>
        public static string HasBanMutators {
            get {
                return ResourceManager.GetString("HasBanMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base mutators picked: 的本地化字符串。
        /// </summary>
        public static string HasSelectBaseMutators {
            get {
                return ResourceManager.GetString("HasSelectBaseMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commander(s) picked: 的本地化字符串。
        /// </summary>
        public static string HasSelectCommanders {
            get {
                return ResourceManager.GetString("HasSelectCommanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free mutators choiced: 的本地化字符串。
        /// </summary>
        public static string HasSelectFreeMutators {
            get {
                return ResourceManager.GetString("HasSelectFreeMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map picked: 的本地化字符串。
        /// </summary>
        public static string HasSelectMap {
            get {
                return ResourceManager.GetString("HasSelectMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nexus co-op Mode 的本地化字符串。
        /// </summary>
        public static string HubMode {
            get {
                return ResourceManager.GetString("HubMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nexus solo mode 的本地化字符串。
        /// </summary>
        public static string HubSoloMode {
            get {
                return ResourceManager.GetString("HubSoloMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(简体) 的本地化字符串。
        /// </summary>
        public static string LangBtn {
            get {
                return ResourceManager.GetString("LangBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊天杯 LiaoTian_Cup v0.3.0 - Programmed by B1ackSand 的本地化字符串。
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map name: 的本地化字符串。
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick map 的本地化字符串。
        /// </summary>
        public static string MapWarn {
            get {
                return ResourceManager.GetString("MapWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multitask mutators: 的本地化字符串。
        /// </summary>
        public static string MultilineMutators {
            get {
                return ResourceManager.GetString("MultilineMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly mutation: 的本地化字符串。
        /// </summary>
        public static string MutationName {
            get {
                return ResourceManager.GetString("MutationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total cost:  的本地化字符串。
        /// </summary>
        public static string MutatorsCost {
            get {
                return ResourceManager.GetString("MutatorsCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Negatvie mutators: 的本地化字符串。
        /// </summary>
        public static string NegativeMutators {
            get {
                return ResourceManager.GetString("NegativeMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pure negative mode 的本地化字符串。
        /// </summary>
        public static string NegativeMutatorsMode {
            get {
                return ResourceManager.GetString("NegativeMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awesome Cmdrs.: 的本地化字符串。
        /// </summary>
        public static string NewCommander {
            get {
                return ResourceManager.GetString("NewCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suck Cmdrs.: 的本地化字符串。
        /// </summary>
        public static string OldCommander {
            get {
                return ResourceManager.GetString("OldCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player(s):  的本地化字符串。
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RandMap: 的本地化字符串。
        /// </summary>
        public static string RandMap {
            get {
                return ResourceManager.GetString("RandMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rand weekly mutations mode 的本地化字符串。
        /// </summary>
        public static string RandMutationsMode {
            get {
                return ResourceManager.GetString("RandMutationsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Bot 的本地化字符串。
        /// </summary>
        public static string RandomBot {
            get {
                return ResourceManager.GetString("RandomBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Bot:  的本地化字符串。
        /// </summary>
        public static string RandomBotStr {
            get {
                return ResourceManager.GetString("RandomBotStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Active 的本地化字符串。
        /// </summary>
        public static string RandomBotStrTip {
            get {
                return ResourceManager.GetString("RandomBotStrTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free choice mutators will show you 8 mutators randomly，player can pick any number of mutators. 的本地化字符串。
        /// </summary>
        public static string RandomMutationTip {
            get {
                return ResourceManager.GetString("RandomMutationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start random 的本地化字符串。
        /// </summary>
        public static string RandomStartBtn {
            get {
                return ResourceManager.GetString("RandomStartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ResetBtn {
            get {
                return ResourceManager.GetString("ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solo mode 的本地化字符串。
        /// </summary>
        public static string SingleMode {
            get {
                return ResourceManager.GetString("SingleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 mutators mode 的本地化字符串。
        /// </summary>
        public static string SixMutatorsMode {
            get {
                return ResourceManager.GetString("SixMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 mutators mode 的本地化字符串。
        /// </summary>
        public static string ThreeMutatorsMode {
            get {
                return ResourceManager.GetString("ThreeMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usuck mode 的本地化字符串。
        /// </summary>
        public static string USuckMode {
            get {
                return ResourceManager.GetString("USuckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dead of Night 的本地化字符串。
        /// </summary>
        public static string 亡者之夜 {
            get {
                return ResourceManager.GetString("亡者之夜", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invasionary Swarm 的本地化字符串。
        /// </summary>
        public static string 侵略虫群 {
            get {
                return ResourceManager.GetString("侵略虫群", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rifts to Korhal 的本地化字符串。
        /// </summary>
        public static string 克哈裂痕 {
            get {
                return ResourceManager.GetString("克哈裂痕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tarsonis 的本地化字符串。
        /// </summary>
        public static string 决战塔桑尼斯 {
            get {
                return ResourceManager.GetString("决战塔桑尼斯", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Malwarfare 的本地化字符串。
        /// </summary>
        public static string 净网行动 {
            get {
                return ResourceManager.GetString("净网行动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chain of Ascension 的本地化字符串。
        /// </summary>
        public static string 升格之链 {
            get {
                return ResourceManager.GetString("升格之链", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hope of the Khalai 的本地化字符串。
        /// </summary>
        public static string 卡莱的希望 {
            get {
                return ResourceManager.GetString("卡莱的希望", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return of the Eternal Dynasty 的本地化字符串。
        /// </summary>
        public static string 君临不灭王朝 {
            get {
                return ResourceManager.GetString("君临不灭王朝", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Masters and Machines 的本地化字符串。
        /// </summary>
        public static string 大师机械 {
            get {
                return ResourceManager.GetString("大师机械", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lock &amp; load 的本地化字符串。
        /// </summary>
        public static string 天界封锁 {
            get {
                return ResourceManager.GetString("天界封锁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dominion Battlegroup 的本地化字符串。
        /// </summary>
        public static string 帝国战斗群 {
            get {
                return ResourceManager.GetString("帝国战斗群", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temple of the Past 的本地化字符串。
        /// </summary>
        public static string 往日神庙 {
            get {
                return ResourceManager.GetString("往日神庙", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machines of War 的本地化字符串。
        /// </summary>
        public static string 战争机械团 {
            get {
                return ResourceManager.GetString("战争机械团", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where the forgotten lie 的本地化字符串。
        /// </summary>
        public static string 探索遗灵之地 {
            get {
                return ResourceManager.GetString("探索遗灵之地", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fleet of the Matriarch 的本地化字符串。
        /// </summary>
        public static string 族长之军 {
            get {
                return ResourceManager.GetString("族长之军", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classic Mech 的本地化字符串。
        /// </summary>
        public static string 旧世机械团 {
            get {
                return ResourceManager.GetString("旧世机械团", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classic Infantry 的本地化字符串。
        /// </summary>
        public static string 旧世步兵团 {
            get {
                return ResourceManager.GetString("旧世步兵团", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadow Tech 的本地化字符串。
        /// </summary>
        public static string 暗影科技团 {
            get {
                return ResourceManager.GetString("暗影科技团", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadow Disruption 的本地化字符串。
        /// </summary>
        public static string 暗影袭扰 {
            get {
                return ResourceManager.GetString("暗影袭扰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mist Opportunities 的本地化字符串。
        /// </summary>
        public static string 机会渺茫 {
            get {
                return ResourceManager.GetString("机会渺茫", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Towering Walkers 的本地化字符串。
        /// </summary>
        public static string 步战机甲 {
            get {
                return ResourceManager.GetString("步战机甲", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cradle of Death 的本地化字符串。
        /// </summary>
        public static string 死亡摇篮 {
            get {
                return ResourceManager.GetString("死亡摇篮", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oblivion Express 的本地化字符串。
        /// </summary>
        public static string 湮灭快车 {
            get {
                return ResourceManager.GetString("湮灭快车", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brooding Corruption 的本地化字符串。
        /// </summary>
        public static string 滋生腐化 {
            get {
                return ResourceManager.GetString("滋生腐化", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Vermillion Problem 的本地化字符串。
        /// </summary>
        public static string 熔火危机 {
            get {
                return ResourceManager.GetString("熔火危机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explosive Threats 的本地化字符串。
        /// </summary>
        public static string 爆炸威胁 {
            get {
                return ResourceManager.GetString("爆炸威胁", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ultimate Blasphemy 的本地化字符串。
        /// </summary>
        public static string 神明亵渎之时 {
            get {
                return ResourceManager.GetString("神明亵渎之时", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raiding Party 的本地化字符串。
        /// </summary>
        public static string 突击团 {
            get {
                return ResourceManager.GetString("突击团", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part &amp; Parcel 的本地化字符串。
        /// </summary>
        public static string 聚铁成兵 {
            get {
                return ResourceManager.GetString("聚铁成兵", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ravaging Infestation 的本地化字符串。
        /// </summary>
        public static string 肆虐扩散 {
            get {
                return ResourceManager.GetString("肆虐扩散", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vanguard of Aiur 的本地化字符串。
        /// </summary>
        public static string 艾尔先锋 {
            get {
                return ResourceManager.GetString("艾尔先锋", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miner Evacuation 的本地化字符串。
        /// </summary>
        public static string 营救矿工 {
            get {
                return ResourceManager.GetString("营救矿工", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Xel`naga Oracle 的本地化字符串。
        /// </summary>
        public static string 萨尔纳加预兆 {
            get {
                return ResourceManager.GetString("萨尔纳加预兆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Void Thrashing 的本地化字符串。
        /// </summary>
        public static string 虚空撕裂 {
            get {
                return ResourceManager.GetString("虚空撕裂", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Void Launch 的本地化字符串。
        /// </summary>
        public static string 虚空降临 {
            get {
                return ResourceManager.GetString("虚空降临", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disruptive Artillery 的本地化字符串。
        /// </summary>
        public static string 袭扰炮击 {
            get {
                return ResourceManager.GetString("袭扰炮击", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devouring Scourge 的本地化字符串。
        /// </summary>
        public static string 遮天蔽日 {
            get {
                return ResourceManager.GetString("遮天蔽日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to the City of Ghosts 的本地化字符串。
        /// </summary>
        public static string 重返亡灵之城 {
            get {
                return ResourceManager.GetString("重返亡灵之城", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real Steel 的本地化字符串。
        /// </summary>
        public static string 铁甲钢拳 {
            get {
                return ResourceManager.GetString("铁甲钢拳", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Siege of Storms 的本地化字符串。
        /// </summary>
        public static string 风暴迫临 {
            get {
                return ResourceManager.GetString("风暴迫临", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scythe of Amon 的本地化字符串。
        /// </summary>
        public static string 黑暗杀星 {
            get {
                return ResourceManager.GetString("黑暗杀星", resourceCulture);
            }
        }
    }
}
