//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiaoTian_Cup.Dictionary.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiaoTian_Cup.Dictionary.I18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Me 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string BackBtn {
            get {
                return ResourceManager.GetString("BackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to menu 的本地化字符串。
        /// </summary>
        public static string BackMenuBtn {
            get {
                return ResourceManager.GetString("BackMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic mutators: 的本地化字符串。
        /// </summary>
        public static string BaseMutator {
            get {
                return ResourceManager.GetString("BaseMutator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick two commanders in Co-op mode 的本地化字符串。
        /// </summary>
        public static string CommanderWarn1 {
            get {
                return ResourceManager.GetString("CommanderWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 you need to pick commander 的本地化字符串。
        /// </summary>
        public static string CommanderWarn2 {
            get {
                return ResourceManager.GetString("CommanderWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string ConfirmBtn {
            get {
                return ResourceManager.GetString("ConfirmBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Co-op mode 的本地化字符串。
        /// </summary>
        public static string DoublesMode {
            get {
                return ResourceManager.GetString("DoublesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free choice mutators: 的本地化字符串。
        /// </summary>
        public static string FreeMutator {
            get {
                return ResourceManager.GetString("FreeMutator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commanders picked: 的本地化字符串。
        /// </summary>
        public static string HasSelectCommanders {
            get {
                return ResourceManager.GetString("HasSelectCommanders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free choice mutators picked: 的本地化字符串。
        /// </summary>
        public static string HasSelectFreeMutators {
            get {
                return ResourceManager.GetString("HasSelectFreeMutators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文(简体) 的本地化字符串。
        /// </summary>
        public static string LangBtn {
            get {
                return ResourceManager.GetString("LangBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map name: 的本地化字符串。
        /// </summary>
        public static string MapName {
            get {
                return ResourceManager.GetString("MapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly mutation name: 的本地化字符串。
        /// </summary>
        public static string MutationName {
            get {
                return ResourceManager.GetString("MutationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pure negative mode 的本地化字符串。
        /// </summary>
        public static string NegativeMutatorsMode {
            get {
                return ResourceManager.GetString("NegativeMutatorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awesome Commander: 的本地化字符串。
        /// </summary>
        public static string NewCommander {
            get {
                return ResourceManager.GetString("NewCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suck Commander: 的本地化字符串。
        /// </summary>
        public static string OldCommander {
            get {
                return ResourceManager.GetString("OldCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player(s):  的本地化字符串。
        /// </summary>
        public static string PlayerName {
            get {
                return ResourceManager.GetString("PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rand weekly mutations mode 的本地化字符串。
        /// </summary>
        public static string RandMutationsMode {
            get {
                return ResourceManager.GetString("RandMutationsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Bot 的本地化字符串。
        /// </summary>
        public static string RandomBot {
            get {
                return ResourceManager.GetString("RandomBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Bot:  的本地化字符串。
        /// </summary>
        public static string RandomBotStr {
            get {
                return ResourceManager.GetString("RandomBotStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Active 的本地化字符串。
        /// </summary>
        public static string RandomBotStrTip {
            get {
                return ResourceManager.GetString("RandomBotStrTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free choice mutators will show you 8 mutators randomly，player can pick any number of mutators. 的本地化字符串。
        /// </summary>
        public static string RandomMutationTip {
            get {
                return ResourceManager.GetString("RandomMutationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start random 的本地化字符串。
        /// </summary>
        public static string RandomStartBtn {
            get {
                return ResourceManager.GetString("RandomStartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ResetBtn {
            get {
                return ResourceManager.GetString("ResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solo mode 的本地化字符串。
        /// </summary>
        public static string SingleMode {
            get {
                return ResourceManager.GetString("SingleMode", resourceCulture);
            }
        }
    }
}
